travis:
  secure:
    BINSTAR_TOKEN: biUNQC8BKmte8a9lPJ7zxKv2YqCjeIpSPOQsmidRXwF5+suvjITS5bYlnNc3DXef4SPVaH88W6MF0DrrrAXeuXVrMDbBR2OOvZpFPcp4JVZcJOGpZjGbeWfxjXEGTQtevDM7zaLIJKlXRy9d9CuhHT/YVzjo8gmzjQZGr/tf/n1VcuxbRU/rT3hxHVvrh/VlyLD9QTH6UMbhDNa7FJtD9u8Z/8mlh9vU3AjVWF6/9+RgMLB6l3ryVIcAnIhDRFiTvdjKG81knI8TKnDomyMALTwp40RUP2bAvcY2wRC0IhYhJohKnOsM5rEINxHAS3jiD6iDFhihuVX9fxMkxzegXtA1UZ2gq+usIikymvBqbxYoZ0mEBHpcPRM80M8EMS6YhXHmH00nRs0s71ty5/N8yXJKSEeXqomTRWFBBH/1rH/drDkC75/+xB2HBQWV8fndj/Jv+TyXQy1cWLPbD4SotuSzxpbfI5FYqcPdxDZRQeGBeA4wJQZLqP2ZJ9elCnaflodwdWsFMq/5LmzJLdfJ38tXQLyGgUcpmrt5dUJSzHH94WgxqGLf00qe5t1YXy/le2KZYmYFXf0OzX4Mpa9DIfSZcy8rXSpAVBVhGiI/dyNTHKTE1csDy6DNziqVOrL8Eab8UjXxdXL6Ai4YyE5twqEXKuPk0B0pQKE2hJzDts0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
