travis:
  secure:
    BINSTAR_TOKEN: Zbk5kWTBvUkswsvNm0JU5j7lcF1CcSg84iogwQ1PosNvjMJtttapJVNLXoDV0pHrqmZRBHTu50w9OvWfxQHksyXVPQYEpISMiFPROnPuGPQaqVxbeNoJxTTLgntXnecmkJBLBKSug72JSawQVuy809/RUKguADYNQKszo85ftid6LPfkLtiG8KFrIrCPgbmXuR1jRA7D/kRYU5nNJIFfih7PCMQlh8m04oOCOZ+y3AFJ1+z7K0D0k+3niDUsDr28P3tN9anYE7bDHN7H96knJ6geVldvET2wC71EgUdYmKyeE+C9xxTT+GQlM35ySSqnmqkrPGSl9KIBZBFMpfl5DLyg7NL0+yP40Sy5t26cMrhrfI/Q+NXPK3UhjOvclmKwMZHazNEpiHK1+vn27d3rkb4vbQah8N3oiO2NAJqQfY/iB4mSIlVdFCDbuWyjTIxRERu8glYpVOAs+K0cGIpn2VZKVXLSZn5FlWIPx8qCfzKoA5pbYC75uJZgqVlOs/lUviKqQQ7TOJvXwTijrC9XCamk4+YShf5+sxaz3awtqqWnybWmEB1Mj+tHk9sDzv6PbXAsmVCPA23ErUxzo443+2gGgkEHglVhjqIDHYz4x6ZBFzq2HtqPCkKfk45O/F+ART7bFeddJxAobyJruvI58sbI1tTV97+DmL2covwR6yg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
